### ISSUE TITLE
Please either include `CHANGELOG.md` in the releases, or skip `test_version_number_match_with_changelog()`

### ISSUE THREAD

**Issue by carygravel** [jacksonllee/iso639#6]
Please either include `CHANGELOG.md` in the releases, or skip `test_version_number_match_with_changelog()` if the changelog is not present.

I am in the process of packaging iso630 for Debian and am using the release from PyPi, which does not include the changelog.

**Comment by jacksonllee** [comment]
Hello! Sorry I'm not quite following here. It's correct that `CHANGELOG.md` isn't included in the PyPI releases at the moment, but neither are the unit tests such as `test_version_number_match_with_changelog`. So how does `CHANGELOG.md` not being present in the PyPI releases become an issue when the PyPI releases also don't have `test_version_number_match_with_changelog`?

**Comment by carygravel** [comment]
The tests are included in the PyPi release.

**Comment by jacksonllee** [comment]
> The tests are included in the PyPi release.

Ah, interesting! In [pyproject.toml](https://github.com/jacksonllee/iso639/blob/4ed61bf3760caaab47cd935254eadd8746db011b/pyproject.toml), nowhere does it specify the inclusion of `tests/` when building a source distribution, but apparently [that's what setuptools does](https://github.com/pypa/setuptools/blob/66a8aee91de7ed8b0f819fb836e5543212e4b860/docs/userguide/miscellaneous.rst?plain=1#L15-L16) (this project's pyproject.toml uses setuptools as the build backend), a behavior I wasn't aware of before.

I've just pushed c2d462d for including `CHANGELOG.md` in the next PyPI source distribution, but I'm not ready to cut this release just yet. Python 3.13 just came out last week, and I'd like the new release to officially support Python 3.13. I'm currently waiting for CircleCI to provide their official Python 3.13 image so that I can turn on CI builds for Python 3.13. The wait should hopefully be just another week or so based on prior experiences with the recent Python 3.x releases. I'll update here when a release is cut.

**Comment by carygravel** [comment]
Cool. Thanks. No need just to cut a release for that change, though. I just patched out the test when I did the packaging.

**Comment by jacksonllee** [comment]
A new release is now on PyPI: https://pypi.org/project/python-iso639/2024.10.22/
I've verified that the source distribution [python_iso639-2024.10.22.tar.gz](https://files.pythonhosted.org/packages/8e/54/f88a3fb5802ce026f8111ab75cafc8d57b2cd455e49cada6a65c28e5726f/python_iso639-2024.10.22.tar.gz) contains `CHANGELOG.md`.
Closing this issue as resolved -- thank you for bringing it to my attention!
